### ISSUE TITLE
교육청 보안 키보드 지원 관련

### ISSUE THREAD

**Issue by start2018** [eduro-hcs/jaga_jindan_automatic_js#3]
현재 이 매크로를 사용중인 사용자입니다.
지난달 부터 자가진단쪽에서 보안키보드를 사용하기 시작하면서 본 매크로가 정상적으로 동작되지 않는데요,
보안 키보드 관련해서는 어떻게 수정하여 다시 작동 시킬 수 있을까요?

**Comment by nnnlog** [comment]
https://github.com/331leo/hcskr_python/pull/23 참고하셔서 직접 수정하시거나 해당 프로그램을 사용하는 것을 추천드립니다.
시간 상의 문제로 관련 프로젝트에 더 이상 유지보수 할 계획이 없습니다.
